apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-users
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    name: pg-data-db-users-0
    namespace: backend-ns
  local:
    path: /mnt/data/db-users
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
          - node-1
