// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Movie struct {
	ID              int32          `json:"id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	DurationMinutes int32          `json:"duration_minutes"`
	ReleaseDate     sql.NullTime   `json:"release_date"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}
