server {
    listen       8080;
    server_name  localhost;
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    resolver kube-dns.kube-system.svc.cluster.local valid=10s ipv6=off;
    
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/movies {
        set $catalog_upstream catalog-service.backend-ns.svc.cluster.local:8082;
        proxy_pass http://$catalog_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/showtimes {
        set $showtime_upstream showtime-service.backend-ns.svc.cluster.local:8083;
        proxy_pass http://$showtime_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/rooms {
        set $showtime_upstream showtime-service.backend-ns.svc.cluster.local:8083;
        proxy_pass http://$showtime_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/bookings {
        set $booking_upstream booking-service.backend-ns.svc.cluster.local:8084;
        proxy_pass http://$booking_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/users/ {
        set $user_upstream user-service.backend-ns.svc.cluster.local:8081;
        proxy_pass http://$user_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
