version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

networks:
  cinema-net:
    driver: bridge

volumes:
  pg_users:
  pg_catalog:
  pg_showtime:
  pg_booking:


services:
  db-users:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: users
    volumes:
      - pg_users:/var/lib/postgresql/data
    networks:
      - cinema-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging

  db-catalog:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: catalog
    volumes:
      - pg_catalog:/var/lib/postgresql/data
    networks:
      - cinema-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging

  db-showtime:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: showtime
    volumes:
      - pg_showtime:/var/lib/postgresql/data
    networks:
      - cinema-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging

  db-booking:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: booking
    volumes:
      - pg_booking:/var/lib/postgresql/data
    networks:
      - cinema-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging

  user-db-migration:
    image: migrate/migrate
    container_name: user-db-migration
    networks:
      - cinema-net
    volumes:
      - ./user-service/db/migration:/migrations
    command:
      - -path=/migrations
      - -database=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db-users:5432/users?sslmode=disable
      - up
    depends_on:
      db-users:
        condition: service_healthy

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD:-postgres}@db-users:5432/users?sslmode=disable
      - JWT_SECRET=${JWT_SECRET:-supersecret}
    depends_on:
      db-users:
        condition: service_healthy
      user-db-migration:
        condition: service_completed_successfully
    networks:
      - cinema-net
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 256M

  catalog-db-migration:
    image: migrate/migrate
    container_name: catalog-db-migration
    networks:
      - cinema-net
    volumes:
      - ./catalog-service/db/migration:/migrations
    command:
      - -path=/migrations
      - -database=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db-catalog:5432/catalog?sslmode=disable
      - up
    depends_on:
      db-catalog:
        condition: service_healthy

  catalog-service:
    build:
      context: ./catalog-service
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD:-postgres}@db-catalog:5432/catalog?sslmode=disable
    depends_on:
      db-catalog:
        condition: service_healthy
      catalog-db-migration:
        condition: service_completed_successfully
    networks:
      - cinema-net
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 256M

  showtime-db-migration:
    image: migrate/migrate
    container_name: showtime-db-migration
    networks:
      - cinema-net
    volumes:
      - ./showtime-service/db/migration:/migrations
    command:
      - -path=/migrations
      - -database=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db-showtime:5432/showtime?sslmode=disable
      - up
    depends_on:
      db-showtime:
        condition: service_healthy

  showtime-service:
    build:
      context: ./showtime-service
    ports:
      - "8083:8083"
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD:-postgres}@db-showtime:5432/showtime?sslmode=disable
    depends_on:
      db-showtime:
        condition: service_healthy
      showtime-db-migration:
        condition: service_completed_successfully
    networks:
      - cinema-net
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 256M

  booking-db-migration:
    image: migrate/migrate
    container_name: booking-db-migration
    networks:
      - cinema-net
    volumes:
      - ./booking-service/db/migration:/migrations
    command:
      - -path=/migrations
      - -database=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db-booking:5432/booking?sslmode=disable
      - up
    depends_on:
      db-booking:
        condition: service_healthy

  booking-service:
    build:
      context: ./booking-service
    ports:
      - "8084:8084"
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD:-postgres}@db-booking:5432/booking?sslmode=disable
    depends_on:
      db-booking:
        condition: service_healthy
      booking-db-migration:
        condition: service_completed_successfully
    networks:
      - cinema-net
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 256M

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      user-service:
        condition: service_started
      catalog-service:
        condition: service_started
      showtime-service:
        condition: service_started
      booking-service:
        condition: service_started
    networks:
      - cinema-net
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 128M
