apiVersion: v1
kind: Secret
metadata:
  name: db-showtime-secret
  namespace: backend-ns
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgrespassword
  DATABASE_URL: postgres://postgres:postgrespassword@db-showtime.backend-ns.svc.cluster.local:5432/showtime?sslmode=disable
