apiVersion: v1
kind: Secret
metadata:
  name: db-users-secret
  namespace: backend-ns
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgrespassword
  DATABASE_URL: postgres://postgres:postgrespassword@db-users.backend-ns.svc.cluster.local:5432/users?sslmode=disable
