apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend/
- frontend/
- 00-backend-ns.yaml
- 00-frontend-ns.yaml

images:
- name: adamad7/frontend
  newTag: "1.0.4"
- name: adamad7/booking-service
  newTag: "1.0.4"
- name: adamad7/catalog-service
  newTag: "1.0.4"
- name: adamad7/showtime-service
  newTag: "1.0.4"
- name: adamad7/user-service
  newTag: "1.0.4"
