apiVersion: v1
kind: Service
metadata:
  name: db-users
  namespace: backend-ns
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: db-users
