// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type Booking struct {
	ID          int32          `json:"id"`
	UserID      int32          `json:"user_id"`
	ShowtimeID  int32          `json:"showtime_id"`
	SeatNumber  string         `json:"seat_number"`
	Status      string         `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	TicketType  sql.NullString `json:"ticket_type"`
	LockedUntil sql.NullTime   `json:"locked_until"`
}
