// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (user_id, showtime_id, seat_number, status)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, showtime_id, seat_number, status, created_at
`

type CreateBookingParams struct {
	UserID     int32  `json:"user_id"`
	ShowtimeID int32  `json:"showtime_id"`
	SeatNumber string `json:"seat_number"`
	Status     string `json:"status"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.UserID,
		arg.ShowtimeID,
		arg.SeatNumber,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShowtimeID,
		&i.SeatNumber,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, user_id, showtime_id, seat_number, status, created_at FROM bookings WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBooking(ctx context.Context, id int32) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShowtimeID,
		&i.SeatNumber,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listBookingsByShowtime = `-- name: ListBookingsByShowtime :many
SELECT id, user_id, showtime_id, seat_number, status, created_at FROM bookings WHERE showtime_id = $1
`

func (q *Queries) ListBookingsByShowtime(ctx context.Context, showtimeID int32) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByShowtime, showtimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShowtimeID,
			&i.SeatNumber,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT id, user_id, showtime_id, seat_number, status, created_at FROM bookings WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByUser(ctx context.Context, userID int32) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShowtimeID,
			&i.SeatNumber,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
