// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const confirmBooking = `-- name: ConfirmBooking :one
UPDATE bookings
SET status = 'reserved', ticket_type = $2, locked_until = NULL
WHERE id = $1 AND user_id = $3 AND status = 'locked' AND locked_until >= NOW()
RETURNING id, user_id, showtime_id, seat_number, status, created_at, ticket_type, locked_until
`

type ConfirmBookingParams struct {
	ID         int32          `json:"id"`
	TicketType sql.NullString `json:"ticket_type"`
	UserID     int32          `json:"user_id"`
}

func (q *Queries) ConfirmBooking(ctx context.Context, arg ConfirmBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, confirmBooking, arg.ID, arg.TicketType, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShowtimeID,
		&i.SeatNumber,
		&i.Status,
		&i.CreatedAt,
		&i.TicketType,
		&i.LockedUntil,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (user_id, showtime_id, seat_number, status, ticket_type)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, showtime_id, seat_number, status, created_at, ticket_type, locked_until
`

type CreateBookingParams struct {
	UserID     int32          `json:"user_id"`
	ShowtimeID int32          `json:"showtime_id"`
	SeatNumber string         `json:"seat_number"`
	Status     string         `json:"status"`
	TicketType sql.NullString `json:"ticket_type"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.UserID,
		arg.ShowtimeID,
		arg.SeatNumber,
		arg.Status,
		arg.TicketType,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShowtimeID,
		&i.SeatNumber,
		&i.Status,
		&i.CreatedAt,
		&i.TicketType,
		&i.LockedUntil,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, user_id, showtime_id, seat_number, status, created_at, ticket_type, locked_until FROM bookings WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBooking(ctx context.Context, id int32) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShowtimeID,
		&i.SeatNumber,
		&i.Status,
		&i.CreatedAt,
		&i.TicketType,
		&i.LockedUntil,
	)
	return i, err
}

const listBookingsByShowtime = `-- name: ListBookingsByShowtime :many
SELECT id, user_id, showtime_id, seat_number, status, created_at, ticket_type, locked_until FROM bookings WHERE showtime_id = $1
`

func (q *Queries) ListBookingsByShowtime(ctx context.Context, showtimeID int32) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByShowtime, showtimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShowtimeID,
			&i.SeatNumber,
			&i.Status,
			&i.CreatedAt,
			&i.TicketType,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT id, user_id, showtime_id, seat_number, status, created_at, ticket_type, locked_until FROM bookings WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByUser(ctx context.Context, userID int32) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShowtimeID,
			&i.SeatNumber,
			&i.Status,
			&i.CreatedAt,
			&i.TicketType,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSeat = `-- name: LockSeat :one
INSERT INTO bookings (user_id, showtime_id, seat_number, status, locked_until)
VALUES ($1, $2, $3, 'locked', $4)
ON CONFLICT (showtime_id, seat_number) DO UPDATE
SET user_id = EXCLUDED.user_id,
    status = 'locked',
    locked_until = EXCLUDED.locked_until
WHERE bookings.status != 'reserved' AND (bookings.status != 'locked' OR bookings.locked_until < NOW())
RETURNING id, user_id, showtime_id, seat_number, status, created_at, ticket_type, locked_until
`

type LockSeatParams struct {
	UserID      int32        `json:"user_id"`
	ShowtimeID  int32        `json:"showtime_id"`
	SeatNumber  string       `json:"seat_number"`
	LockedUntil sql.NullTime `json:"locked_until"`
}

func (q *Queries) LockSeat(ctx context.Context, arg LockSeatParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, lockSeat,
		arg.UserID,
		arg.ShowtimeID,
		arg.SeatNumber,
		arg.LockedUntil,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShowtimeID,
		&i.SeatNumber,
		&i.Status,
		&i.CreatedAt,
		&i.TicketType,
		&i.LockedUntil,
	)
	return i, err
}
