apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: frontend-ns-dev
data:
  DOMAIN: dev-cinema.mazadonia.cc
  BOOKING_SVC_EXTERNAL: booking-service.backend-ns-dev.svc.cluster.local
  CATALOG_SVC_EXTERNAL: catalog-service.backend-ns-dev.svc.cluster.local
  SHOWTIME_SVC_EXTERNAL: showtime-service.backend-ns-dev.svc.cluster.local
  USER_SVC_EXTERNAL: user-service.backend-ns-dev.svc.cluster.local
