// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"
)

type Room struct {
	ID            int32           `json:"id"`
	Name          string          `json:"name"`
	Capacity      int32           `json:"capacity"`
	SeatingLayout json.RawMessage `json:"seating_layout"`
}

type Showtime struct {
	ID        int32     `json:"id"`
	MovieID   int32     `json:"movie_id"`
	RoomID    int32     `json:"room_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Type      string    `json:"type"`
}
