apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend-ns
spec:
  hard:
    pods: "20"
    requests.cpu: "3"
    requests.memory: "3Gi"
    limits.cpu: "8"
    limits.memory: "8Gi"
