apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backends
  namespace: backend-ns
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - user-service
      - catalog-service
      - showtime-service
      - booking-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from frontend namespace and Ingress Controllers
  - from:
    - namespaceSelector:
        matchLabels:
          name: frontend-ns
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 8081
    - protocol: TCP
      port: 8082
    - protocol: TCP
      port: 8083
    - protocol: TCP
      port: 8084
  egress:
  # Allow egress to CoreDNS
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow egress to PostgreSQL databases in the same namespace
  - to:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - db-users
          - db-catalog
          - db-showtime
          - db-booking
    ports:
    - protocol: TCP
      port: 5432
  # Allow schema migrations during initContainer to fetch database schema
  - to:
    - podSelector:
        matchLabels:
          app: db-users
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: db-catalog
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: db-showtime
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: db-booking
    ports:
    - protocol: TCP
      port: 5432
