apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-booking
  namespace: backend-ns
spec:
  serviceName: db-booking
  replicas: 1
  selector:
    matchLabels:
      app: db-booking
  template:
    metadata:
      labels:
        app: db-booking
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: booking
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-booking-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
        - name: tmp-volume
          mountPath: /tmp
        - name: run-volume
          mountPath: /run/postgresql
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi
