apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-ns

resources:
- ../../../base/frontend
- ./environment-config.yaml

replacements:
- source:
    kind: ConfigMap
    name: environment-config
    fieldPath: data.DOMAIN
  targets:
  - select:
      kind: Ingress
      name: cinema-ingress
    fieldPaths:
    - spec.rules.0.host

