apiVersion: v1
kind: Secret
metadata:
  name: db-booking-secret
  namespace: backend-ns
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgrespassword
  DATABASE_URL: postgres://postgres:postgrespassword@db-booking.backend-ns.svc.cluster.local:5432/booking?sslmode=disable
