apiVersion: v1
kind: Secret
metadata:
  name: db-catalog-secret
  namespace: backend-ns
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgrespassword
  DATABASE_URL: postgres://postgres:postgrespassword@db-catalog.backend-ns.svc.cluster.local:5432/catalog?sslmode=disable
